Add pull request template
CodeWithAloha/CWAWebsite pull request #29
Opened 2023-09-25 03:42 UTC by sarafurd

2023-09-28 21:07 UTC, Alexandra-Haynes requested changes

2023-09-28 21:07 UTC, Alexandra-Haynes commented on PULL_REQUEST_TEMPLATE.md
Let's also turn this instructions into HTML comments. This will ensure that the text is seen only by the person filling in the template and not in the final description. Comments are not rendered, so they won't appear in the final description. Example:
```
<!-- 
Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".
-->
# Summary:
```

We could also inform the contributor that the comments are for guidance and will not appear in the final PR description by adding a note in the beginning of the template:
```
<!-- 
NOTE: The comments enclosed in these brackets are guides and will not be visible in your pull request description. Please make sure to fill out all the sections as necessary and remove the comments before submitting your PR.

Please provide a brief description of the changes made in this PR for the "Code with Aloha Website".
-->
# Summary:
```

Thank you, Sara! We appreciate your time and support!
Let me know if you have questions

2023-09-28 23:19 UTC, sarafurd commented on PULL_REQUEST_TEMPLATE.md
Yeah no problem

2023-09-29 01:16 UTC, Alexandra-Haynes commented
Also, let's make the subtitles smaller, I'm thinking ### should be fine. Ex: 
```
### Summary:
``` 
for all subtitles

2023-09-29 19:55 UTC, Alexandra-Haynes requested changes
![Screenshot 2023-09-29 095351](https://github.com/CodeWithAloha/CWAWebsite/assets/113944962/6e6bc9b3-3e4e-4664-9133-7aefdbc97de0)
Please read our discussion again and preview your md file, let me know if you have questions

2023-10-02 03:29 UTC, sarafurd commented
> Sara, let's use the html comments for all the instructions, not just the summary section. In the end, all the explanations below all the subtitles will be commented out, so they will not be rendered in the final template. Thank you for your quick response!
to

2023-10-02 03:29 UTC, closed without merging